openapi: 3.0.0
info:
  title: API de Tareas
  description: API para gestionar tareas en una aplicación de ejemplo.
  version: 1.0.0
paths:
  /tarea/todas:
    get:
      summary: Obtener todas las tareas
      operationId: obtenerTareas
      responses:
        '200':
          description: Lista de tareas obtenidas exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TareaModel'

  /tarea:
    post:
      summary: Guardar una nueva tarea
      operationId: guardarTarea
      requestBody:
        description: La tarea a guardar.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TareaModel'
        required: true
      responses:
        '200':
          description: Tarea guardada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TareaModel'

  /tarea/{id}:
    get:
      summary: Obtener una tarea por ID
      operationId: obtenerTareaPorId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Tarea obtenida exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TareaModel'
        '404':
          description: Tarea no encontrada.

    delete:
      summary: Eliminar una tarea por ID
      operationId: eliminarTareaId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Tarea eliminada exitosamente.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Tarea no encontrada.

components:
  schemas:
    TareaModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        completed:
          type: boolean
      required:
        - title
        - completed
